### PR TITLE
Update the macOS installation instructions

### PR DESCRIPTION
**Pull request by jybleau**
Based on #87 and others. (Issue #87 could then be closed)
brew links update is not supported anymore.
qt5 is now named simply qt and stored in directories with the same name.
It worked fine under both my Catalina Mac with latest brew 2.2.6.

### CODE REVIEW

**Comment by doliG** [comment]
@tpisto Hello, can you have a look at this PR ?

**Comment by tiholic** [comment]
@tpisto The changes look good. Works well for me on Catalina 10.15.4

**Comment by frxnz** [comment]
I don't know if this is specific to my machine but I also had to run `brew install pkg-config`. I didn't have the path mentioned in the readme (`/opt/X11/lib/pkgconfig`). This is on Catalina 10.15.5.

**Comment by steveCluster** [comment]
Thank you @frxnz.  `brew install pkg-config` also fixed my installation issue that was erroring in `gyp`.  I suggest this PR be updated with that.

**Comment by jybleau** [comment]
I've updated the PR.
@tiholic can you review the new commit?
Thanks

**Review by tiholic — APPROVED** [review]

**Comment by tiholic** [comment]
@jybleau verified, and working good on my machine.

**Pull request merged**
