### PR TITLE
imgpdf improvements

### PR DESCRIPTION
**Pull request by tsdgeos**
You can specify:
 * Number of cores in which the pages will be rendered in parallel
 * Scale the pages are rendered (1 = 72 dpi, 0.2 = 360 dpi)
 * Whether the render has antialias or not

Parallelizing the rendering saves some time (even not as much as one
would hope) since the saving back to pdf is still done one page after
the other.

Using antialias allows for decreasing the dpi while still getting a
reasonable enough quality.

### CODE REVIEW

**Comment by tpisto** [comment]
This is absolutely fantastic, thank you! Do I dare to ask you also to upgrade README.md to document the new parameters and the changes. Let's say version number after this upgrade would be 3.1.0.

**Comment by tsdgeos** [comment]
README.MD updated

**Comment by emilsedgh** [comment]
Hi there. Any updates on merging this?

**Comment by florianbepunkt** [comment]
@tpisto Any chance of merging this?

**Comment by florianbepunkt** [comment]
@tsdgeos I tried to try out your fork, but I guess you would also need to update the installation instructions. I'm on mac and installing your fork via npm fails because QMutex class is not available

**Comment by tpisto** [comment]
Thank you for your pull request! What's your name? I would like to add it to the list of contributors. I'm very pleased to see that so many has been willing to push this library forward!

**Comment by emilsedgh** [comment]
That is Albert Astals Cid, Poppler's maintainer.

**Comment by florianbepunkt** [comment]
@tsdgeos thank you, i prepended QtCore to the includes you added but installation still fails. I followed the recommended installation routine with homebrew
```

2017-12-20 12:11:25.117 xcodebuild[71177:791382] [MT] PluginLoading: Required plug-in compatibility UUID E0A62D1F-3C18-4D74-BFE5-A4167D643966 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2017-12-20 12:11:25.118 xcodebuild[71177:791382] Failed to load plugin at: /Users/floriannorbertbepunkt/Library/Application Support/Developer/Shared/Xcode/Plug-ins/Unity4XC.xcplugin, skipping.  Reason for failure: *** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]
  CXX(target) Release/obj.target/pdf_fill_form/src/pdf-fill-form.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePopplerAsync.o
  CXX(target) Release/obj.target/pdf_fill_form/src/NodePoppler.o
In file included from ../src/NodePoppler.cc:21:
In file included from /usr/local/include/QtCore/QThreadPool:1:
In file included from /usr/local/include/QtCore/qthreadpool.h:45:
/usr/local/include/QtCore/qthread.h:163:43: error: 'future<void>' is unavailable: introduced in macOS 10.8
    static QThread *createThreadImpl(std::future<void> &&future);
                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/future:1279:52: note: 'future<void>' has
      been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS _LIBCPP_AVAILABILITY_FUTURE future<void>
                                                   ^
1 error generated.
make: *** [Release/
```

**Comment by florianbepunkt** [comment]
Okay, quick follow up in case anyone else comes across the same problem. This is an issue with Qt5.10 on mac (at least on el capitan). Installing an older version and prepending the new include as stated by @tsdgeos solves the issue.

**Comment by jpickwell** [comment]
Just add `/usr/local/include/QtCore` to the end of the `CPATH` environment variable, assuming a `brew link --force qt`. I have `CPATH`, `LD_LIBRARY_PATH`, and `PKG_CONFIG_PATH` set in my `.bashrc` file.

```bash
function update_path_variable()
{
  local paths="${!1}"
  local new_paths="$2"

  if [[ -z "${paths}" ]]; then
    paths="${new_paths}"
  else
    paths="${new_paths}:${paths}"
  fi

  export "$1=${paths}"
}

update_path_variable CPATH "${HOME}/include:/usr/local/include/QtCore"
#update_path_variable LIBRARY_PATH "${HOME}/lib:/usr/X11/lib:/usr/local/lib:/lib:/usr/lib"
update_path_variable LD_LIBRARY_PATH "${HOME}/lib:/usr/X11/lib:/usr/local/lib:/lib:/usr/lib"
#update_path_variable DYLD_LIBRARY_PATH "${LIBRARY_PATH}"
update_path_variable DYLD_FALLBACK_LIBRARY_PATH "${LIBRARY_PATH}"
update_path_variable MANPATH "${HOME}/share/man:${HOME}/man:/usr/bin/man:/usr/X11/share/man:/usr/local/share/man:/usr/share/man"
update_path_variable PATH "${HOME}/bin:/usr/local/opt/openssl/bin:${HOME}/projects/chromium/tools/depot_tools"
update_path_variable PKG_CONFIG_PATH "${HOME}/lib/pkgconfig:/usr/X11/lib/pkgconfig:/usr/local/lib/pkgconfig:/lib/pkgconfig:/usr/lib/pkgconfig"
```

**Pull request merged**
